import 'dart:io';
import 'package:archive/archive_io.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

import '../models/renpy_project.dart';

/// Produces a directory tree that Ren'Py's launcher can open directly,
/// including the minimum options.rpy/gui files a real project expects,
/// then zips it up for sharing/export.
class RenPyExportService {
  static const _screensStub = '''
# Auto-generated by Ren'Py Studio Mobile.
# Replace/extend with real screens.rpy content from `renpy new` if needed.
''';

  static String _optionsRpy(String projectName) => '''
define config.name = _("$projectName")
define gui.show_name = True
define config.version = "1.0"

define build.name = "${projectName.replaceAll(' ', '')}"

define config.window_icon = "gui/window_icon.png"

# Exported by Ren'Py Studio Mobile.
''';

  /// Writes game/script.rpy (+ any extra script files), game/options.rpy,
  /// character defines, and copies imported images into game/images.
  Future<Directory> materialize(RenPyProject project) async {
    final gameDir = Directory(p.join(project.directoryPath, 'game'));
    await gameDir.create(recursive: true);
    await Directory(p.join(gameDir.path, 'images')).create(recursive: true);
    await Directory(p.join(gameDir.path, 'audio')).create(recursive: true);
    await Directory(p.join(gameDir.path, 'gui')).create(recursive: true);

    // options.rpy (only write if it doesn't already exist so user edits stick)
    final optionsFile = File(p.join(gameDir.path, 'options.rpy'));
    if (!await optionsFile.exists()) {
      await optionsFile.writeAsString(_optionsRpy(project.name));
    }

    // screens.rpy stub if missing
    final screensFile = File(p.join(gameDir.path, 'screens.rpy'));
    if (!await screensFile.exists()) {
      await screensFile.writeAsString(_screensStub);
    }

    // character defines + compiled script files
    final defines =
        project.characters.map((c) => c.toRenPyDefine()).join('\n');
    for (final script in project.scripts) {
      final isFirst = script.id == project.scripts.first.id;
      final file = File(p.join(gameDir.path, script.fileName));
      final body = script.compile();
      await file.writeAsString(isFirst ? '$defines\n\n$body' : body);
    }

    // copy imported images (source paths -> game/images/<basename>)
    for (final imgPath in project.importedImagePaths) {
      final src = File(imgPath);
      if (await src.exists()) {
        final dest = File(p.join(gameDir.path, 'images', p.basename(imgPath)));
        await src.copy(dest.path);
      }
    }

    return Directory(project.directoryPath);
  }

  /// Zips the full project directory (the folder Ren'Py's launcher expects
  /// to see, i.e. containing `game/`) and returns the .zip file.
  Future<File> exportZip(RenPyProject project) async {
    await materialize(project);

    final tempDir = await getTemporaryDirectory();
    final zipPath =
        p.join(tempDir.path, '${_safeFileName(project.name)}.zip');

    final encoder = ZipFileEncoder();
    encoder.create(zipPath);
    await encoder.addDirectory(Directory(project.directoryPath),
        includeDirName: true);
    encoder.close();

    return File(zipPath);
  }

  String _safeFileName(String name) =>
      name.trim().replaceAll(RegExp(r'[^A-Za-z0-9_\-]'), '_');
}
